### ISSUE TITLE
enable different bespoke model cache dir

### ISSUE THREAD

**Issue by BioinfoTongLI** [weigertlab/spotiflow#15]
Current the pretrained model are saved to the user home folder
https://github.com/weigertlab/spotiflow/blob/main/spotiflow/model/pretrained.py#L24-L25

**Describe the solution you'd like**
Would be great to support custume directory to facilitate HPC runs.

**Comment by AlbertDominguez** [comment]
Hi @BioinfoTongLI, thanks for bringing this up! i just released a version which allows changing the cache directory where models (and datasets) are saved. You can just set an env var now (`SPOTIFLOW_CACHE_DIR`) and, if it exists, it will use that directory instead (see [here](https://github.com/weigertlab/spotiflow?tab=readme-ov-file#changing-the-cache-directory)). That should facilitate the HPC runs :)
