### ISSUE TITLE
Disable global logging level INFO.

### ISSUE THREAD

**Issue by JoOkuma** [weigertlab/spotiflow#17]
hi @AlbertDominguez,

Some modules of spotiflow change the level of the global logging, for example, https://github.com/weigertlab/spotiflow/blob/f991ada6b577942b50ae5f945b2352b2e187c23c/spotiflow/utils/matching.py#L8-L9

From my understanding, using like this, would be preferred so only the current logger level is changed
 https://github.com/weigertlab/spotiflow/blob/f991ada6b577942b50ae5f945b2352b2e187c23c/spotiflow/cli/predict.py#L15-L16

**Comment by AlbertDominguez** [comment]
You're damn right @JoOkuma! Just pushed the changes, the new release to PyPi should be up in a few minutes (and I realized we discussed this back in Woods Hole, sorry for the delay!) Lmk if it does not work as expected 🙂

**Comment by JoOkuma** [comment]
Thank you for the quick solution, @AlbertDominguez  
It worked for me.
