### ISSUE TITLE
Fig 1e from the preprint blank?

### ISSUE THREAD

**Issue by ajinkya-kulkarni** [weigertlab/spotiflow#2]
Hello team, thanks again for this repo. I was reading the preprint and I noticed that Fig 1e appears blank? Is this a rendering issue?

Best, Ajinkya

**Comment by AlbertDominguez** [comment]
Hi Ajinkya,

Thanks for your interest in our work! The lines are actually there, but there is apparently a rendering issue in some browsers. I think you should be able to see it if you download the PDF and open it in any other software. In any case, here it is:

![image](https://github.com/weigertlab/spotiflow/assets/31998088/a4ba7919-7655-4d8c-8d60-70682ba635cf)

We'll try to solve it and upload a new version in due time :)

Albert

**Comment by ajinkya-kulkarni** [comment]
Ah nice, thanks for the image!

**Comment by maweigert** [comment]
Hi @ajinkya-kulkarni 

Which browser did you use to preview the pdf?

**Comment by ajinkya-kulkarni** [comment]
Google Chrome - Version 121.0.6167.139 (Official Build) (64-bit)

**Comment by maweigert** [comment]
thanks! indeed, can reproduce (works fine on firefox & safari). Weird
