### ISSUE TITLE
Retrieve spot size

### ISSUE THREAD

**Issue by ajinkya-kulkarni** [weigertlab/spotiflow#22]
Hi Albert, thanks again for keeping this repo active.
I noticed you implemented the spot size as an output - can you maybe upload an example script?
My current project will benefit a lot from the spot sizes!

Best, Ajinkya

**Comment by AlbertDominguez** [comment]
Hi Ajinkya,

From the CLI, simply doing `spotiflow-predict ... --estimate-params true` should give the sizes (FWHM of each spot) in the exported CSV.
From the API, you can simply pass an argument named `fit_params` when calling the `.predict()` method:

```python
from spotiflow.model import Spotiflow

img = ...
model = Spotiflow.from_folder(...)
spots, details = model.predict(img, ..., fit_params=True)
```
you can then find the estimated FWHM of each spot in `details.fit_params.fwhm`. I'll try to upload a sample script soon but this should suffice.

Note that this is still a bit experimental, so any feedback is more than welcome! 🙂

**Comment by ajinkya-kulkarni** [comment]
Thanks, will try it out!

**Comment by AlbertDominguez** [comment]
Closing for now, feel free to reopen if something comes up!
