### ISSUE TITLE
Spot diameter from the heatmap or flowmap

### ISSUE THREAD

**Issue by ajinkya-kulkarni** [weigertlab/spotiflow#5]
Hello team, thanks again for this repo. I was wondering if there is a way to retrieve the spot diameters for each detected spot.

**Comment by maweigert** [comment]
Indeed a nice idea! However the predicted heatmap will try to recover the ground truth Gaussians, which have a fixed sigma (e.g. 1.5px). So its is not really predicting the "spot diameter"

**Comment by ajinkya-kulkarni** [comment]
Sorry, another question - does the length of the flow more or less predict the spot size? If so, is there a way to expose them as well in the predictions?

**Comment by maweigert** [comment]
No, unfortunately not. As the annotation spotiflow is trained on are only single points annotations, there is no natural target for such a diameter.

**Comment by AlbertDominguez** [comment]
Hmm I don't think so. As @maweigert suggested, similarly to the heatmap, the stereographic flow is designed to predict using a specific scale length, and it should not convey any information about the spot size. 

> Ah ok, I see. In that case, there should be some way to start seeding a circle at each predicted spot (x,y) and "constantly" look at the original image to see whether a big enough seed was generated.

I think this is probably a safer way if you want to proceed to compute the spot size, at least for now

**Comment by ajinkya-kulkarni** [comment]
Alright, thanks for the help!
