### ISSUE TITLE
Add bioconda/conda-forge support

### ISSUE THREAD

**Issue by migueLib** [weigertlab/spotiflow#8]
I'm using and adding spotiflow as an NF-core module. I have already created a docker container for it and expanded the CLI. 

nf-core best practices require the tool to be available via bioconda (ideally) or conda-forge + container. Do you have a timeline/plans to add spotiflow as a bioconda/conda-forge package.

Thanks, :)

**Comment by AlbertDominguez** [comment]
Hi Miguel,

I actually thought of putting up a conda package at some point rather soon :)
Didn't have a specific channel in mind (thought of `conda-forge` mostly, but could be `bioconda` too). I'll check it out when I'm a bit more free, but I think I'll be able to do it in the following weeks. I'll let you know here when that happens :)

**Comment by migueLib** [comment]
Hi Albert,

Thank you very much for the response! I'm very much looking forward to it. Plese let me know how/if I can assist with this in any way! ;)

**Comment by migueLib** [comment]
Hi Albert,

Thanks a lot for pushing this forward! I also just did the PR for the extended CLI and added the Workflow for Docker.

**Comment by AlbertDominguez** [comment]
Hi Miguel,

The package was just merged to conda-forge, can be installed with
`conda install -c conda-forge spotiflow`.

Closing this for now, but please let me know if you find any incidence with the package!

**Comment by migueLib** [comment]
Fantastic news!
