### ISSUE TITLE
Extend CLI parameters

### ISSUE THREAD

**Issue by migueLib** [weigertlab/spotiflow#9]
I would like to make use of the CLI for processing my data, unfortunately some very useful parameters are not accessible via the CLI. 

I had already fork your repo and implemented the required changes. It doesn't change the baseline functionality it just gives access to the rest of the configurable parameters. 

Please let me know if you would be ok with me PRing those changes. 

Bests, :)

**Comment by AlbertDominguez** [comment]
We're very happy to accept contributions so please, go ahead with the PR! :)

**Comment by AlbertDominguez** [comment]
Closed by #11
